# Generated by Django 3.2.9 on 2021-12-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2002)),
                ('budget', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=20)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_clube', to='myapp2.club')),
            ],
        ),
    ]
