# Generated by Django 3.2.9 on 2022-01-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name': 'Известные женьшины', 'verbose_name_plural': 'Известные женьшины'},
        ),
    ]
